name: test-cov

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  # id-token: write  # needed if you choose OIDC auth for Codecov

jobs:
  test-cov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install system dependencies for PyAudio on GitHub Actions' Ubuntu env
      - name: Install system libs (PortAudio)
        run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev libasound2-dev

      # https://docs.astral.sh/uv/guides/integration/github/
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.15"

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests with coverage
        run: uv run pytest --cov=src --cov-report=xml --cov-report=term-missing --cov-fail-under=20

      # Upload coverage to Codecov (Action v5)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
